### ISSUE TITLE
Is some data missing from DHRA?

### ISSUE THREAD

**Issue by ptsefton** [Arkisto-Platform/ohrm-jsonld-exporter#2] opened 2023-05-01 22:24 UTC
The exported script reports that some sources and targets of relationships are missing, eg 
 
```
Can't find source: #E000451
```

But looking for that ID in the SQL data it looks like there is no entity -- it only appears in relationships.

```
grep data/DHRA-sql/* -e E000451 
data/DHRA-sql/DHRAdat2000.sql:INSERT INTO EFRSHIP ( eid,fid,description,rating,efstartdate,efsdatemod,efstart,efenddate,efedatemod,efend,efplace,efplacestate,efplacecountry,efcitation,efprepared,efnote,efappenddate,eflastmodd,ordering ) VALUES (E'E000451',E'F000017',NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2006-08-14 11:59:11','2006-08-14 12:00:01','0' );
data/DHRA-sql/DHRAdat2000.sql:INSERT INTO RELATEDENTITY ( eid,reid,rerelationship,redescription,restartdate,resdatemod,restart,reenddate,reedatemod,reend,redatequal,renote,rerating,reappenddate,relastmodd,reprepared,reorder ) VALUES (E'E000026',E'E000451',E'Related',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','2006-08-14 12:01:43','2006-08-14 12:01:43',NULL,'0' );
data/DHRA-sql/DHRAdat2000.sql:INSERT INTO RELATEDENTITY ( eid,reid,rerelationship,redescription,restartdate,resdatemod,restart,reenddate,reedatemod,reend,redatequal,renote,rerating,reappenddate,relastmodd,reprepared,reorder ) VALUES (E'E000349',E'E000451',E'Related',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','2006-08-14 12:01:28','2006-08-14 12:01:28',NULL,'0' );
data/DHRA-sql/DHRAdat2000.sql:INSERT INTO RELATEDENTITY ( eid,reid,rerelationship,redescription,restartdate,resdatemod,restart,reenddate,reedatemod,reend,redatequal,renote,rerating,reappenddate,relastmodd,reprepared,reorder ) VALUES (E'E000350',E'E000451',E'Related',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','2006-08-14 12:01:38','2006-08-14 12:01:38',NULL,'0' );
data/DHRA-sql/DHRAdat2000.sql:INSERT INTO RELATEDENTITY ( eid,reid,rerelationship,redescription,restartdate,resdatemod,restart,reenddate,reedatemod,reend,redatequal,renote,rerating,reappenddate,relastmodd,reprepared,reorder ) VALUES (E'E000384',E'E000451',E'Related',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','2006-08-14 12:01:13','2006-08-14 12:01:13',NULL,'0' );
data/DHRA-sql/DHRAdat2000.sql:INSERT INTO RELATEDENTITY ( eid,reid,rerelationship,redescription,restartdate,resdatemod,restart,reenddate,reedatemod,reend,redatequal,renote,rerating,reappenddate,relastmodd,reprepared,reorder ) VALUES (E'E000451',E'E000384',E'Related',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','2006-08-14 12:01:09','2006-08-14 12:01:12',NULL,'0' );
data/DHRA-sql/DHRAdat2000.sql:INSERT INTO RELATEDENTITY ( eid,reid,rerelationship,redescription,restartdate,resdatemod,restart,reenddate,reedatemod,reend,redatequal,renote,rerating,reappenddate,relastmodd,reprepared,reorder ) VALUES (E'E000451',E'E000349',E'Related',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','2006-08-14 12:01:14','2006-08-14 12:01:27',NULL,'0' );
data/DHRA-sql/DHRAdat2000.sql:INSERT INTO RELATEDENTITY ( eid,reid,rerelationship,redescription,restartdate,resdatemod,restart,reenddate,reedatemod,reend,redatequal,renote,rerating,reappenddate,relastmodd,reprepared,reorder ) VALUES (E'E000451',E'E000350',E'Related',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','2006-08-14 12:01:29','2006-08-14 12:01:37',NULL,'0' );
data/DHRA-sql/DHRAdat2000.sql:INSERT INTO RELATEDENTITY ( eid,reid,rerelationship,redescription,restartdate,resdatemod,restart,reenddate,reedatemod,reend,redatequal,renote,rerating,reappenddate,relastmodd,reprepared,reorder ) VALUES (E'E000451',E'E000026',E'Related',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','2006-08-14 12:01:39','2006-08-14 12:01:43',NULL,'0' );
˜`

**Comment by marcolarosa** [comment] 2023-05-02 23:01
No. At least highly unlikely.

The OHRM works by creating rows in various tables and manages associations in code rather than via DB associations. I expect the issue is that something was deleted but references were not cleaned up and the db wasn't there to enforce referential integrity.

**Comment by marcolarosa** [comment] 2023-05-07 05:29
Closing as complete.

**Closed as completed by marcolarosa** 2023-05-07 05:29 UTC
